[project]
name = "lecture-openai-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=2.6.0",
    "python-env>=1.0.0",
]
